image: maven:3.3.3-jdk-8
stages:
  - build
  - deploy
build_job:
  stage: build
  only:
    - master
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true
  tags:
    - docker
build_merge_job:
  stage: build
  except:
    - master
    - tags
  script:
    - git merge origin master --no-commit --no-ff
    - mvn --batch-mode compile -Dmaven.test.skip=true
  tags:
    - docker
deploy_job:
  stage: deploy
  only:
    - master
  script:
    - mvn --batch-mode deploy -Dmaven.test.skip=true
  artifacts:
    paths:
      - /target/sonar-gitlab-plugin-1.3.0-SNAPSHOT.jar
  tags:
    - docker
deploy_tags_job:
  stage: deploy
  only:
    - tags
  script:
    - mvn --batch-mode org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=$CI_BUILD_REF_NAME -DgenerateBackupPoms=false
    - mvn --batch-mode deploy -Dmaven.test.skip=true
  artifacts:
    paths:
      - /target/sonar-gitlab-plugin-$CI_BUILD_REF_NAME.jar
  tags:
    - docker